"""Add current_streak

Revision ID: 3719be649238
Revises: b168ec3dbe2a
Create Date: 2026-07-07 23:32:05.071507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3719be649238'
down_revision: Union[str, None] = 'b168ec3dbe2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'current_streak')
    # ### end Alembic commands ###
