"""add dark_mode to user profile

Revision ID: 3c60959c1540
Revises: 80a39d09796f
Create Date: 2026-07-08 00:35:25.440446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c60959c1540'
down_revision: Union[str, None] = '80a39d09796f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('dark_mode', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'dark_mode')
    # ### end Alembic commands ###
