"""Add title and avatar_url

Revision ID: 80a39d09796f
Revises: 3719be649238
Create Date: 2026-07-07 23:45:58.475176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a39d09796f'
down_revision: Union[str, None] = '3719be649238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('title', sa.Text(), server_default='Explorador Novato', nullable=False))
    op.add_column('user_profiles', sa.Column('avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'avatar_url')
    op.drop_column('user_profiles', 'title')
    # ### end Alembic commands ###
