"""Initial schema

Revision ID: b168ec3dbe2a
Revises: 
Create Date: 2026-07-06 18:21:53.847809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b168ec3dbe2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS citext')
    op.create_table('challenge_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level_id_at_start', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('answered_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.Column('xp_delta', sa.Integer(), nullable=False),
    sa.Column('accuracy_session', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('started_xp', sa.Integer(), nullable=False),
    sa.Column('ended_xp', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('generation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('IN_PROGRESS','FINISHED','ABANDONED')", name='check_status_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumer_processed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consumer_name', sa.Text(), nullable=False),
    sa.Column('outbox_event_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('PROCESSED','SKIPPED','FAILED')", name='check_consumer_status_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.Text(), nullable=False),
    sa.CheckConstraint("run_type IN ('FULL','INCREMENTAL')", name='check_run_type_valid'),
    sa.CheckConstraint("status IN ('RUNNING','SUCCESS','FAILED')", name='check_leaderboard_status_valid'),
    sa.CheckConstraint("triggered_by IN ('SCHEDULER','EVENT_WORKER','MANUAL')", name='check_triggered_by_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('xp_total', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.SmallInteger(), nullable=False),
    sa.Column('accuracy_global', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_event_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_rules',
    sa.Column('level_id', sa.SmallInteger(), nullable=False),
    sa.Column('xp_min', sa.Integer(), nullable=False),
    sa.Column('xp_max', sa.Integer(), nullable=False),
    sa.Column('level_up_cost', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level_up_cost > 0', name='check_level_cost_positive'),
    sa.CheckConstraint('xp_max >= xp_min', name='check_xp_max_valid'),
    sa.CheckConstraint('xp_min >= 0', name='check_xp_min_positive'),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_table('outbox_event_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outbox_event_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.Text(), nullable=False),
    sa.Column('topic_or_queue', sa.Text(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','PUBLISHED','FAILED')", name='check_outbox_status_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prepost_test_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('test_type', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('score_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("test_type IN ('PRE_TEST','POST_TEST')", name='check_test_type_valid'),
    sa.CheckConstraint('duration_seconds >= 0', name='check_prepost_duration_valid'),
    sa.CheckConstraint('score >= 0', name='check_prepost_score_positive'),
    sa.CheckConstraint('score_percent >= 0 AND score_percent <= 100', name='check_prepost_score_percent_valid'),
    sa.CheckConstraint('total_questions > 0', name='check_prepost_total_questions_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('option_key', sa.Text(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position BETWEEN 1 AND 6', name='check_position_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_topics',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('topic_key', sa.Text(), nullable=False),
    sa.Column('topic_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_key')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.SmallInteger(), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('language_code', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('AI','CURATED','FALLBACK')", name='check_source_type_valid'),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='check_difficulty_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('session_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_question_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_key', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feedback_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_question_id')
    )
    op.create_table('session_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('order_in_session', sa.SmallInteger(), nullable=False),
    sa.Column('difficulty_at_delivery', sa.SmallInteger(), nullable=False),
    sa.Column('topic_id', sa.SmallInteger(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_results',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('xp_before', sa.Integer(), nullable=False),
    sa.Column('xp_gained', sa.Integer(), nullable=False),
    sa.Column('xp_lost', sa.Integer(), nullable=False),
    sa.Column('xp_after_raw', sa.Integer(), nullable=False),
    sa.Column('xp_after_floor', sa.Integer(), nullable=False),
    sa.Column('xp_after_final', sa.Integer(), nullable=False),
    sa.Column('level_before', sa.SmallInteger(), nullable=False),
    sa.Column('level_after', sa.SmallInteger(), nullable=False),
    sa.Column('level_up', sa.Boolean(), nullable=False),
    sa.Column('floor_applied', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('user_auth_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('xp_total', sa.Integer(), nullable=False),
    sa.Column('current_level_id', sa.SmallInteger(), nullable=False),
    sa.Column('accuracy_global', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_answered', sa.Integer(), nullable=False),
    sa.Column('total_correct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accuracy_global >= 0 AND accuracy_global <= 100', name='check_accuracy_valid'),
    sa.CheckConstraint('total_answered >= 0', name='check_total_answered_positive'),
    sa.CheckConstraint('total_correct >= 0 AND total_correct <= total_answered', name='check_total_correct_valid'),
    sa.CheckConstraint('xp_total >= 0', name='check_xp_total_positive'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('xp_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.Text(), nullable=False),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_type IN ('GAIN','LOSS','ADJUSTMENT','FLOOR_PROTECTION')", name='check_entry_type'),
    sa.CheckConstraint('balance_after >= 0', name='check_balance_after_positive'),
    sa.CheckConstraint('balance_before >= 0', name='check_balance_before_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xp_ledger')
    op.drop_table('users')
    op.drop_table('user_profiles')
    op.drop_table('user_auth_sessions')
    op.drop_table('session_results')
    op.drop_table('session_questions')
    op.drop_table('session_answers')
    op.drop_table('questions')
    op.drop_table('question_topics')
    op.drop_table('question_options')
    op.drop_table('prepost_test_attempts')
    op.drop_table('outbox_events')
    op.drop_table('outbox_event_deliveries')
    op.drop_table('level_rules')
    op.drop_table('learning_event_log')
    op.drop_table('leaderboard_snapshots')
    op.drop_table('leaderboard_runs')
    op.drop_table('consumer_processed_events')
    op.drop_table('challenge_sessions')
    # ### end Alembic commands ###
